import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import MobileDrawer from "@/components/MobileDrawer";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 flex items-center justify-between">
          <Link href="/">
            <Image 
              src='/image_assets/Logo.png'
              alt="Guild Logo"
              width={175}
              height={58}
              priority
              className="w-48 sm:w-52 md:w-60 lg:w-72"
            />
          </Link>
          <NavBar />
          <MobileDrawer />
        </header>
        {children}
      </body>
    </html>
  );
}
